Resources:
  MyEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: my-eks-cluster
      RoleArn: !GetAtt MyEKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds:
          - subnet-xxxxxxxxxx   # Specify the subnet IDs where the EKS cluster will be deployed
        SecurityGroupIds:
          - sg-xxxxxxxxxx       # Specify the security group IDs for the EKS cluster

  MyEKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: my-eks-cluster-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  MyEKSUser:
    Type: AWS::IAM::User
    Properties:
      UserName: my-eks-user

  MyEKSUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref MyEKSUser

Outputs:
  MyEKSClusterName:
    Value: !Ref MyEKSCluster
  MyEKSUserName:
    Value: !Ref MyEKSUser
  MyEKSUserAccessKeyId:
    Value: !Ref MyEKSUserAccessKey
  MyEKSUserSecretAccessKey:
    Value: !GetAtt MyEKSUserAccessKey.SecretAccessKey
