Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: my-vpc

  MySubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-1a
      Tags:
        - Key: Name
          Value: my-subnet1

  MySubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Name
          Value: my-subnet2

  MyPlacementGroup1:
    Type: AWS::EC2::PlacementGroup
    Properties:
      Strategy: cluster
      PlacementGroupName: my-placement-group1

  MyPlacementGroup2:
    Type: AWS::EC2::PlacementGroup
    Properties:
      Strategy: cluster
      PlacementGroupName: my-placement-group2

  MyEC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-xxxxxxxxxx  # Specify the desired AMI ID
      InstanceType: t2.micro   # Specify the instance type
      KeyName: my-key-pair    # Specify the key pair name for SSH access
      SecurityGroupIds:
        - sg-xxxxxxxxxx       # Specify the security group ID(s) for the instance
      SubnetId: !Ref MySubnet1
      PlacementGroupName: !Ref MyPlacementGroup1

  MyEC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-xxxxxxxxxx  # Specify the desired AMI ID
      InstanceType: t2.micro   # Specify the instance type
      KeyName: my-key-pair    # Specify the key pair name for SSH access
      SecurityGroupIds:
        - sg-xxxxxxxxxx       # Specify the security group ID(s) for the instance
      SubnetId: !Ref MySubnet2
      PlacementGroupName: !Ref MyPlacementGroup2

Outputs:
  MyVPCId:
    Value: !Ref MyVPC
  MySubnet1Id:
    Value: !Ref MySubnet1
  MySubnet2Id:
    Value: !Ref MySubnet2
  MyPlacementGroup1Name:
    Value: !Ref MyPlacementGroup1
  MyPlacementGroup2Name:
    Value: !Ref MyPlacementGroup2
  MyEC2Instance1Id:
    Value: !Ref MyEC2Instance1
  MyEC2Instance2Id:
    Value: !Ref MyEC2Instance2
